[package]
name = "main"
version = "0.1.0"
authors = ["David Peklak <dpeklak@gmail.com>"]
edition = "2018"

[dependencies]
histo-graph-core = { path = "../core" }
serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0.39"
