[package]
name = "main"
version = "0.1.0"
authors = ["David Peklak <dpeklak@gmail.com>"]
edition = "2018"

[dependencies]
histo-graph-core = { path = "../core" }
histo-graph-file = { path = "../file" }
clap = "2.33.0"
